version: '3'
services:
  app:
    image: node:alpine
    volumes:
      - .:/app
      - data:/data
    working_dir: /app
    environment:
      - NODE_ENV=local
    command: npm start
    ports:
      - 8080:8080

volumes:
  data:
